Make the business profile page fetch data
Code-the-Dream-School/gg-pac-team5-front pull request #24
Opened 2024-08-01 23:31 UTC by CHEUNG-K-Jeffrey

2024-08-03 22:11 UTC, Pisotski requested changes

2024-08-03 22:11 UTC, Pisotski commented on src/main.jsx
> +        loader: async ({ params }) => {
Please move loader to Pages component and export it.

Otherwise Browser router will become unreadable. It will also improve readability of pages component in isolation

2024-08-04 02:38 UTC, CHEUNG-K-Jeffrey commented on src/main.jsx
> +        loader: async ({ params }) => {
Okay, done.

2024-08-04 06:53 UTC, Pisotski approved these changes

2024-08-04 15:58 UTC, merged