Added deployed backend URL
Code-the-Dream-School/gg-pac-team5-front pull request #60
Opened 2024-09-12 19:30 UTC by AnujaBujurge29

- solved minor bugs
-

2024-09-12 19:38 UTC, Pisotski requested changes

2024-09-12 19:38 UTC, Pisotski commented on src/Pages/Services/FetchAPI.jsx
> +    const API_URL = "https://gg-pac-team5-back-1.onrender.com/api/v1/vendors"
please import API from config file.
we keep it in .env file. If server host will change, your component will break again

import { API } from "../../config";

const API_URL=`${API}/services/vendorId/${vendorId}`

2024-09-12 19:38 UTC, Pisotski commented on src/Pages/Services/Cards.jsx
> +        const API_URL = "https://gg-pac-team5-back-1.onrender.com/api/v1/vendors"
same here

2024-09-13 02:46 UTC, AnujaBujurge29 commented on src/Pages/Services/FetchAPI.jsx
> +    const API_URL = "https://gg-pac-team5-back-1.onrender.com/api/v1/vendors"
Resolved

2024-09-13 02:46 UTC, AnujaBujurge29 commented on src/Pages/Services/Cards.jsx
> +        const API_URL = "https://gg-pac-team5-back-1.onrender.com/api/v1/vendors"
Resolved

2024-09-13 16:53 UTC, Pisotski approved these changes

2024-09-13 17:01 UTC, merged